### ISSUE TITLE
7205, <?xml version="1.0" encoding="UTF-8"?> <response result="7205" message="soap body parsing fail." />

### ISSUE THREAD

**Issue by Shantanu-tec** [inka-pallycon/pallycon-widevine-android-sdk#1]
When i play it by using my url and token it throws this error.

        String urlMine = "someUrl.mpd";
       
        
        String tokenMine = "someToken";
       

        PallyConDrmConfigration config = new PallyConDrmConfigration(
                "someSiteId",
                "someSiteKey",
                tokenMine,
                "",
                null,
                null,
                "https://license-global.pallycon.com/ri/licenseManager.do",
                UUID.fromString((C.WIDEVINE_UUID).toString())
        );
   

     

        ContentData content = new ContentData(urlMine, "", config);

        // TODO: 2. initialize PallyconWVM SDK
        WVMAgent = PallyConWvSDK.createPallyConWvSDK(this, content);
        WVMAgent.setPallyConEventListener(drmListener);
        MediaSource mediaSource = null;
        try {
            mediaSource = WVMAgent.getMediaSource();
        } catch (PallyConException.ContentDataException e) {
            e.printStackTrace();
            return;
        } catch (PallyConException.DetectedDeviceTimeModifiedException e) {
            e.printStackTrace();
            return;
        }
        if ((WVMAgent.getDrmInformation().getLicenseDuration() <= 0 || WVMAgent.getDrmInformation().getPlaybackDuration() <= 0) && WVMAgent.getDownloadState() == DownloadState.COMPLETED) {
            Toast.makeText(this, "Expired License", Toast.LENGTH_SHORT).show();
            return;
        }

        // player setting
        player = new ExoPlayer.Builder(/* context= */ this)
                .setTrackSelector(trackSelector)
                .build();
        player.setMediaSource(mediaSource);
        player.addListener(playerEventListener);
        playerView.setPlayer(player);
        player.setPlayWhenReady(true);

        player.prepare();

**Comment by Inkayuyu04** [comment]
Please check the tokenMine value.
The 7205 license error occurs when the value of the token is incorrect.
For more information, please contact us through PallyCon helpdesk and you will get an accurate answer.
